# Generated by Django 4.2.6 on 2024-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_remove_review_name_review_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gener',
        ),
        migrations.AddField(
            model_name='movie',
            name='gener',
            field=models.ManyToManyField(null=True, to='Movie.gener'),
        ),
    ]
