# Generated by Django 4.2.6 on 2024-01-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_remove_movie_gener_movie_gener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='comment',
        ),
    ]
