# Generated by Django 4.2.6 on 2024-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_review_rate_alter_review_movies_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gener',
            field=models.ManyToManyField(to='Movie.gener'),
        ),
    ]
